### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jan2000** [flesniak/python-prodj-link#1]
Great project. What is the license for this project? I would like to contribute if it under a permissive license like MIT, BSD etc.

**Comment by flesniak** [comment]
Eww, seems I forgot adding a license. Usually I publish my stuff with GPLv3, but I would be fine with an Apache or BSD license.

**Comment by flesniak** [comment]
Fixed with commit cb86fdf60667c8ac3495dcc31fd763f42b1f8f5d.
