### ISSUE TITLE
Other wave forms in .EXT

### ISSUE THREAD

**Issue by brunchboy** [flesniak/python-prodj-link#10]
Current versions of rekordbox seem to also write `PWV4` and `PWV5` tags in the `.ext` file, which are bigger and much bigger waveforms, with color information. There is some analysis of the `PWV4` payload here: https://github.com/Deep-Symmetry/dysentery/issues/9

**Comment by flesniak** [comment]
I already worked on colored waveforms half a year ago, but I somehow lost focus. Maybe I'll push my experiments, but they are not much more than what jan2000 commented in this issue.

**Comment by brunchboy** [comment]
Very understandable! There is so much we can work on, and we only have what time we can volunteer, I have the same problem continually. Thanks so much for all your incredible reverse-engineering work.

**Comment by brunchboy** [comment]
I think we can close this based on what @jan2000 submitted.
