### ISSUE TITLE
Construct v2.9 support

### ISSUE THREAD

**Issue by PouleR** [flesniak/python-prodj-link#2]
Construct v2.9 doesn't have the String class anymore, therefore the packets.py comes with an error:

ImportError: cannot import name 'String'

Construct v2.8.21 is the version that must be used to run this script

**Comment by flesniak** [comment]
Thanks for reporting. I'm already on it, but I did not finish yet. as Construct v2.9 partially removed support for embedding structs, I'll have to refactor code in several files.
Maybe I can finish it next weekend.

**Comment by flesniak** [comment]
Construct v2.9 is now supported, but not inside the master branch. Some distributions (i.e. Ubuntu) still have construct 2.8 in their repositories, thus support for 2.8 is still necessary. Changes for v2.9 were partially not backwards compatible and reside in the [construct-v2.9 branch](/flesniak/python-prodj-link/tree/construct-v2.9).

Some internal changes were necessary. I did some testing and basic functionality is ok, but I may have missed some lines. Please report bugs with respect to construct v2.9 here.
