### ISSUE TITLE
Retrieval of IP / Netmask / MAC on Mac OS X not working

### ISSUE THREAD

**Issue by PouleR** [flesniak/python-prodj-link#3]
The methods

- get_ip_linux
- get_netmask_linux
- get_mac_linux

Are not working on a Mac OS X system, the ioctl calls are throwing an exception. Another way to retrieve the data could be by using this package (which works on Mac OS X):

https://pypi.org/project/netifaces/

**Comment by flesniak** [comment]
Thanks for the heads up, I'll be looking into that package as soon as I have some spare time.

**Comment by PouleR** [comment]
@flesniak I've created an implementation but I'm not sure if it works on other systems (haven't tested it). I will create a pull request for this.
