### ISSUE TITLE
Unknown switch identified

### ISSUE THREAD

**Issue by brunchboy** [flesniak/python-prodj-link#9]
In [track.py line 46](https://github.com/flesniak/python-prodj-link/blob/master/pdblib/track.py#L46) there is a definition for:

    "unknown_switch" / IndexedPioString(6), # "ON" or empty

and I have figured out through experimentation that this is the rekordbox “Public” setting for the track (in the Info pane, next to the track title), which I believe controls whether it is shared over Kuvo when you play it.

**Comment by flesniak** [comment]
Updated with commit 51017db5fd78745ee25db79c96a9de132bdc06a9. Thanks!
